//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWireframes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TImagen
    {
        public int ID { get; set; }
        public byte[] Imagen { get; set; }
        public Nullable<int> ID_Evento { get; set; }
    
        public virtual TEventos TEventos { get; set; }
    }
}
